# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				egg = true
				zoglin = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				llama = true
				skeleton = true
				bat = true
				husk = true
				hoglin = true
				experience_bottle = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wither_skeleton = true
				wandering_trader = true
				vex = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				llama_spit = true
				mooshroom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				ravager = true
				trader_llama = true
				donkey = true
				tropical_fish = true
				fox = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				blaze = true
				piglin = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				illusioner = true
				potion = true
				trident = true
				wither_skull = true
				villager = true
				wolf = true
				skeleton_horse = true
				fishing_bobber = true
				zombie_villager = true
				elder_guardian = true
				boat = true
				small_fireball = true
				polar_bear = true
				strider = true
				hopper_minecart = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				wither = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.myloot]
				loot_chest_minecart = true

			[light_sources.settings.entities.homebodies_fantasy]
				mountable_hidden_entity = true

			[light_sources.settings.entities.fishofthieves]
				devilfish = true
				splashtail = true
				stormfish = true
				wrecker = true
				ancientscale = true
				battlegill = true
				wildsplash = true
				plentifin = true
				islehopper = true
				pondie = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.graveyard]
				revenant = true
				skeleton_creeper = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.goblintraders]
				vein_goblin_trader = true
				goblin_trader = true

			[light_sources.settings.entities.hedgehog]
				hedgehog = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true

			[light_sources.settings.entities.pigeons]
				pigeon = true

			[light_sources.settings.entities.boatcontainer]
				chest_boat = true

			[light_sources.settings.entities.wildlife]
				snail = true
				spicebush_butterfly = true
				monkey = true
				possum = true
				ladybug = true
				morpho_butterfly = true
				cottonbird = true
				boar = true
				anteater = true
				hermitcrab = true
				armadillo = true
				glasswing_butterfly = true
				tiger_butterfly = true
				phoebe = true
				beaver = true
				june_beetle = true
				python = true
				chameleon = true
				hamster = true
				stickbug = true
				milk_snake = true
				grass_snake = true
				bluebird = true
				gecko = true
				hedgehog = true
				deer = true
				rhino_beetle = true
				robin = true
				dragonfly = true
				iguana = true
				king_snake = true
				staghorn_beetle = true
				sparrow = true
				porcupine = true
				lark = true
				swallow = true
				oriole = true
				flycatcher = true
				ant = true
				monarch_butterfly = true
				towhee = true
				sunflowerbeetle = true
				goldfinch = true
				chickadee = true
				badger = true
				wren = true
				cricket = true
				spider = true
				ferret = true
				white_eye = true
				crab = true
				meadowlark = true

