generateCabins = true
moddedLootInChests = true
extractinatorSupport = true
techLoot = "MODERN_INDUSTRIALIZATION"

[defaultCabin]
enabled = true
spacing = 36
separation = 34
minHeight = 3
maxHeight = 42

[deepslateCabin]
enabled = true
spacing = 36
separation = 34
minHeight = -56
maxHeight = -3

[desertCabin]
enabled = true
spacing = 35
separation = 34
minHeight = 3
maxHeight = 44

[mesaCabin]
enabled = true
spacing = 34
separation = 33
minHeight = 3
maxHeight = 48

[taigaCabin]
enabled = true
spacing = 35
separation = 34
minHeight = 3
maxHeight = 48

[iceCabin]
enabled = true
spacing = 34
separation = 33
minHeight = 3
maxHeight = 42

[jungleCabin]
enabled = true
spacing = 34
separation = 33
minHeight = 3
maxHeight = 44

[oceanCabin]
enabled = true
spacing = 38
separation = 36
minHeight = 24
maxHeight = 44
